---
services:
  - type: web
    name: telegram-whatsapp-forwarder
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: WHATSAPP_GROUP_ID
        sync: false
    disk:
      name: whatsapp-session
      mountPath: /opt/render/project/src/whatsapp_session
      sizeGB: 1